image: node:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd server && npm install
  cache:
    paths:
      - server/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - server/node_modules/

test:
  stage: test
  dependencies:
    - build
  script:
    - cd server && npm run test


# from M Frydrychowicz
lint:
  stage: test
  before_script:
    - npm install -g eslint
  script:
    - eslint --ext .js .

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
variables:
  SAST_EXCLUDED_ANALYZERS: "semgrep"



